### ISSUE TITLE
Requirements in Denmark to run this? and hardware needed?

### ISSUE THREAD

**Issue by KlavsKlavsen** [tiede/kamstrup-mqtt#2]
As I understand it from https://www.version2.dk/blog/faa-indsigt-dit-elforbrug-1092934 you use an esp8266 - but do you also have an arduino -or is that all that is needed?
and you state something about requireing encryption keys from the power operator (SEAS in my case) - where do you request this?

I would REALLY appreciate a short summary on how to use the code in this github :)

**Comment by tiede** [comment]
Hi Klavs - all you need is en ESP8266, two wires and a usb charger for powering the ESP8266.

You need to get the encryption keys from your elnet provider. In my case it is radius and they provide the following contact page

https://radiuselnet.dk/elkunder/elmaaleren/betjening/
